### ISSUE TITLE
Walkengine needs to filter incoming walk command somehow

### ISSUE THREAD

**Issue by Jade-Fountain** [NUbots/NUbots#10]
The walk path planner sends varying walk speed commands to the walkengine which may be causing a lack of smoothness in the leg motions

**Comment by josiahw** [comment]
The walk skill should be in charge of this. If it's done in the walk engine, we'll end up with the overshoot problems we had in the old walk. You need the component that smooths the walk commands to have some notion of the future plans.

**Comment by ysims** [comment]
Implemented in #1061 in Director
