### ISSUE TITLE
Director modules crash if started with robot fallen over

### ISSUE THREAD

**Issue by Tom0Brien** [NUbots/NUbots#1067]

**Comment by ysims** [comment]
I've added this to the bugs list in #975 975

**Comment by KipHamiltons** [comment]
👃smells like Asan might be helpful (I hear c++ crash and I smell Asan, let's be real)

**Comment by KipHamiltons** [comment]
👃smells like Asan might be helpful (I hear c++ crash and I smell Asan, let's be real)
