### ISSUE TITLE
Transform3D inverse needs attention

### ISSUE THREAD

**Issue by JakeFountain** [NUbots/NUbots#18]
Given two Transform3D objects, A and B, the operation (A \* B).i() will use the armadillo inverse computation instead of the affine inverse for homogeneous matrices.

**Comment by BrendanAnnable** [comment]
Unfortunately this is a limitation on the part of armadillo and their "glue" types, we could possibly patch Transform3D to handle it but I haven't looked too deeply into it.

The solution is to wrap it in a constructor, i.e.  Transform3D(A * B).i()

**Comment by Bidski** [comment]
Or overload `operator*` to handle Transform3D type?

**Comment by KipHamiltons** [comment]
We have removed `Transform3D`. Closing.
