### ISSUE TITLE
Hardware Issues

### ISSUE THREAD

**Issue by ejcatt** [NUbots/NUbots#21]
### Darwin6
- [ ] Top-right screw hole in torso backplate is damaged
### Motors
- [ ] MX28#038, MX28#071, MX28#096: Servo broken
- [ ] RX28M#118: Encoder issue
- [ ] MX28#???x2: Replace gears

**Comment by Bidski** [comment]
Darwin#3 Neck motor needs replacing -- fixed

iGus#1 Needs power supply -- known issue, won't fix.

**Comment by Bidski** [comment]
Darwin #1: Right leg has gangrene is necrotic. Amuptation from the thigh down is required.

**Comment by Bidski** [comment]
Darwin#1: Right leg has gangrene is necrotic. Amuptation from the thigh down is required -- surgery was a success
Dawrin#2 Head loose, needs screwing in -- fixed

**Comment by TrentHouliston** [comment]
Out of date
