### ISSUE TITLE
Pass flags directly to ninja

### ISSUE THREAD

**Issue by KipHamiltons** [NUbots/NUbots#401]
Currently the `b` script sits between us and our builds. This is good _basically all of the time_, but you could probably think of specific cases where having full access to ninja's capabilities/flags would be useful. Having a way to pass flags to ninja without using `./b shell` and calling ninja manually might be nice.

**Comment by CMurtagh-LGTM** [comment]
We already can.
Eg `./b build -- --version` returns the version of ninja.

**Comment by KipHamiltons** [comment]
Yes, we can since #477 was merged :stuck_out_tongue: 
We certainly could not before that.
