### ISSUE TITLE
GameController Responses in Webots

### ISSUE THREAD

**Issue by ysims** [NUbots/NUbots#495]
Currently, when running the official RoboCup controller our robot experiences many penalties until it gets sent into the time out corner. We need to track down the problems, which are probably related to the way we handle GameController messages.

**Comment by LachlanCourt** [comment]
I might be able to help with this? What's the best way to start?

**Comment by ysims** [comment]
Make a role that is identical to robocup but with webots instead of darwin::hardwareio.

Then run the robocup controller in webots and the role in NUbots. Config for the robocup controller is in the nubots/webots fork.

**Comment by ysims** [comment]
Now I'm wondering if it does have issues or not. I might be misremembering and it's just the keyboardwalk that has this problem (obvs because it doesn't do game controller things). Still should test and verify it though.

**Comment by ysims** [comment]
The issue has been fixed with a change in configuration file `team_1.json` over at NUbots/webots. We also respond the GameController as of #503.
