### ISSUE TITLE
Examine strange scope in DataLogging

### ISSUE THREAD

**Issue by KipHamiltons** [NUbots/NUbots#602]
DataLogging has a strange scope in its Configuration reaction. I don't think it does anything. I have made a todo in it in #600 
 to look at it after robocup lol. it's [here](https://github.com/NUbots/NUbots/pull/600/files/c769bebfc20594671029e7a1dc8dcd9d770b5188#diff-795f9944aedfac4346946fe24173c3e410203e7872e37ba16faff3ae578b61c8R116)

**Comment by TrentHouliston** [comment]
It does nothing, looks like somone just it { too many times
