### ISSUE TITLE
Plot Juggler could be interesting for NUsight charts

### ISSUE THREAD

**Issue by KipHamiltons** [NUbots/NUbots#611]
@TheCoolKidsTable has mentioned that [Plot Juggler](https://github.com/facontidavide/PlotJuggler) is worth investigating. Apparently it has features that chart view does not. Please elaborate @TheCoolKidsTable

**Comment by KipHamiltons** [comment]
github magic :D

**Comment by TheCoolKidsTable** [comment]
It looks to be fairly straightforward to setup. I think it'll handle the large amount of data coming in better than charts. Has some nice features like multiple charts at once, plotting data on both x and y (useful for stuff like position). Simple drag and drop data. 

Downside is it will have to sit outside standalone from  nusight I'm pretty sure.

**Comment by TrentHouliston** [comment]
Seems pretty cool!, you should be able to just write a simple module to grab the NUsight charts and others and use one of the many many streaming interfaces it supports!

**Comment by KipHamiltons** [comment]
Did we not add this?

**Comment by JosephusPaye** [comment]
The PR to add it (#878) is not merged yet. We'll close this once that gets in.

**Comment by JosephusPaye** [comment]
Fixed in https://github.com/NUbots/NUbots/pull/878
