### ISSUE TITLE
Static build

### ISSUE THREAD

**Issue by KipHamiltons** [NUbots/NUbots#619]
Building statically doesn't work. We should fix that.
To fix it, it'll basically consist of turning on static builds using `./b configure -i`, then fixing the errors that it makes. You MUST `./b configure --clean -- -DSTATIC_LIBRARIES=ON` to turn on static builds though, because (IIRC) once you configure without static libraries on, you can't turn them on properly (I am probably misremembering this somehow, but that command is guaranteed to set you on the right path I think).

**Comment by CMurtagh-LGTM** [comment]
We might want to add this to CI when its done, so it doesn't break in the future.

**Comment by CMurtagh-LGTM** [comment]
@KipHamiltons
Looks like this will have some complications with the weak-linkage used in glibc.
https://stackoverflow.com/questions/3430400/linux-static-linking-is-dead

**Comment by TrentHouliston** [comment]
And that is why glibc is garbage and musl is best
