### ISSUE TITLE
Per Robot Config

### ISSUE THREAD

**Issue by deevus** [NUbots/NUbots#7]

**Comment by deevus** [comment]
@TrentHouliston 

I remember you saying that config files are aggregated in some way? There's so much code in the project so it would be great if you could point me in the general direction.

Can you explain how it currently works in explicit terms? What command do I call to generate a config? Without any changes what is the current process? (once again I'd like an explicit explanation so I can investigate the invocation)

Sorry if I'm being a pain here but the sheer amount of code is pretty overwhelming.

**Comment by comicxmz001** [comment]
Same question to Simon. The explicit terms.

**Comment by comicxmz001** [comment]
@deevus 
If you want the config files about servos, sensors, limbIDs, they are located at NUbots\shared\messages\input .

Some other config files, such as field configs, you may find it from NUbots\modules\support\configuration

That's what I know, hope it helps. :P

**Comment by deevus** [comment]
@comicxmz001 Thanks. I'll have a look

**Comment by deevus** [comment]
Starting point: https://github.com/NUbots/NUbots/blob/develop/tools/cmake/NUClearModuleBuilder.cmake#L40-L60

Thanks @mitchellmetcalfe

**Comment by deevus** [comment]
https://github.com/NUbots/NUbots/blob/develop/tools/scripts/send.py
https://github.com/NUbots/NUbots/blob/develop/modules/support/configuration/ConfigSystem/src/ConfigSystem.h
https://github.com/NUbots/NUbots/blob/develop/shared/messages/support/Configuration.h

**Comment by TrentHouliston** [comment]
Fixed
