### ISSUE TITLE
Lean in the walk 

### ISSUE THREAD

**Issue by ysims** [NUbots/NUbots#752]
It seems that the quintic walk has an obvious lean - without telling it to turn, it turns. This is noticed in webots, and unlikely to be the robot model (I think someone said it's mirrored). Should check out the quintic walk and find out what's wrong. Tracing the path that the splines take may help.

**Comment by ysims** [comment]
@TheCoolKidsTable @PiiDish lol apparently this isnt the first time we've thought about this

**Comment by ysims** [comment]
@Tom0Brien @Crafty15 @PiiDish Tom fixed this in #910 right?

**Comment by Crafty15** [comment]
> @Tom0Brien @Crafty15 @PiiDish Tom fixed this in #910 right?

I haven't noticed it on the robots but i've heard Jason say it still happens in webots. Although i'm not if his that branch was up to date at the time.

**Comment by PiiDish** [comment]
I'm pretty sure it doesn't happen anymore. If it does it isn't as pronounced as it was. The last optimisation runs I did it wasn't happening at all

**Comment by ysims** [comment]
Fixed in issue mentioned above.
