### ISSUE TITLE
We should purge the word "darwin" from our codebase

### ISSUE THREAD

**Issue by KipHamiltons** [NUbots/NUbots#758]
I have been putting off updating #443 until we removed the word "darwin" from things. I have started to do it a couple of times before becoming inevitably distracted by something else shiny, since it was slightly more work than trivial.

Resolving this issue would include things such as removing the `darwin` namespace, renaming filenames with the word "darwin" in them, updating any old docs which reference darwins, and updating readmes, such as those changed in #443.

**Comment by ysims** [comment]
Should be purged as of merging #802.
