### ISSUE TITLE
LLVM fails to build due to memory consumption

### ISSUE THREAD

**Issue by Tom0Brien** [NUbots/NUbots#826]
When running `./b target generic -b` LLVM can cause system to run out of memory preventing the build from completing.

To overcome this a workaround is change `ninja` to `ninja -jX` where X is less threads than maximum available within:  https://github.com/NUbots/NUbots/blob/9eadc26cca710ee575909683e1cfbbb231b3e21b/docker/usr/local/bin/install-from-source#L160

Maybe `-jX` could be added as an option for the command `./b target generic -b` . For example: `./b target generic -b -j8`

**Comment by TheCoolKidsTable** [comment]
Potential fix provided by @Bidski : limiting docker to use less cores and less ram may also be a viable option (one that doesn't in you having to rebuild the entire the docker image)
https://docs.docker.com/engine/reference/run/#runtime-constraints-on-resources
