### ISSUE TITLE
Port the current behaviour system to the Director

### ISSUE THREAD

**Issue by TrentHouliston** [NUbots/NUbots#975]
Porting everything to the director will require transforming/creating modules to the director.
This issue exists to track what still remains

### Actuation

- [X] Servo #973
- [X] Servo Groups #973
- [X] IK #973
- [X] Servo Sequences #981
- [X] Scripts #992 #994

### Skills

- [x] GetUp #998 
- [x] Falling Relax #1002 
- [x] Walk #1029
- [x] Look #1020
- [x] Kick #995

### Planners

- [x] Walk path planner #1037 
- [x] Look Planner #1027 
- [x] Kick Planner #1006 
- [x] GetUpPlanner #1001
- [x] FallingRelaxPlanner #1002

### Strategy

- [x] WalkToBall #1040 
- [x] KickTowardsGoal #1088
- [x] LookAtBall #1027 
- [x] FallingRecovery #1003 

### Purpose

- [x] Striker #1056 
- [x] Goalie #1065
- [x] RoboCup #1058

**Comment by ysims** [comment]
[actuation, motion, skills, planning, strategy, purpose]

**Comment by ysims** [comment]
Reminder to self about the watcher seg fault when the watchers are equal (remove_watcher_double with no priority set).
Also the memory problems in director tests, unrelated.

**Comment by ysims** [comment]
Closing this since "porting behaviour system to Director" is done and bugs are moved to #1125.
